### PR TITLE
Upgrade expo SDK to 50

### PR DESCRIPTION
**Pull request by karanr3ddy**

### CODE REVIEW

**Review by akinncar — CHANGES_REQUESTED** [review]
did you run in your machine? it needs some extra config plus maybe libs bumps

stacktrace on `yarn`:
```sh
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

stacktrace on `yarn web`:
```sh
PluginError: Package "expo-font" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Unexpected token 'export'
```

**Comment by karanr3ddy** [comment]
@akinncar Can you pull latest code and try running `yarn`. it should work fine now

**Comment by akinncar** [comment]
the app starts but it shows a blank screen with a lot of errors on the console
probably need some changes on expo-gl and web-gl libs to make it work

**Comment by karanr3ddy** [comment]
Yeah, it's not working on web but it works on expo app.

**Comment by akinncar** [comment]
ah ok, nice!
can you fix the web too? otherwise we can't merge

**Comment by karanr3ddy** [comment]
Can you take latest code and try again. it should work on web also now.

**Review by akinncar — APPROVED** [review]
LGTM ❤️

**Pull request merged**
